const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const KEY="frostpos_v1";
const demoProducts=[
{id:"p1",name:"Vanilla Cloud",category:"Ice Cream",price:18000,stock:24,emoji:"🍦"},
{id:"p2",name:"Chocolate Bliss",category:"Ice Cream",price:20000,stock:18,emoji:"🍫"},
{id:"p3",name:"Strawberry Pop",category:"Ice Cream",price:20000,stock:21,emoji:"🍓"},
{id:"p4",name:"Matcha Mist",category:"Special",price:24000,stock:12,emoji:"🍵"},
{id:"p5",name:"Blueberry Sky",category:"Special",price:23000,stock:9,emoji:"🫐"},
{id:"p6",name:"Mango Splash",category:"Ice Cream",price:19000,stock:15,emoji:"🥭"},
{id:"p7",name:"Cookies & Cream",category:"Ice Cream",price:22000,stock:17,emoji:"🍪"},
{id:"p8",name:"Iced Latte",category:"Drink",price:18000,stock:10,emoji:"🥤"},
{id:"p9",name:"Caramel Crunch",category:"Topping",price:6000,stock:30,emoji:"🍯"}
];
let state=JSON.parse(localStorage.getItem(KEY)||"null")||{products:demoProducts,transactions:[],cart:[],settings:{store:"FrostPOS Ice Cream",cashier:"Rindu"}};
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const money=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
const toast=(m)=>{let t=$("#toast");t.textContent=m;t.classList.add("show");clearTimeout(window.tt);window.tt=setTimeout(()=>t.classList.remove("show"),2200)};
function renderCategories(){let cats=["Semua",...new Set(state.products.map(p=>p.category))];$("#categoryChips").innerHTML=cats.map((c,i)=>`<button class="chip ${i===0?"active":""}" data-cat="${c}">${c}</button>`).join("");$$(".chip").forEach(b=>b.onclick=()=>{$$(".chip").forEach(x=>x.classList.remove("active"));b.classList.add("active");renderProducts(b.dataset.cat,$("#productSearch").value)})}
function renderProducts(cat="Semua",q=""){let arr=state.products.filter(p=>(cat==="Semua"||p.category===cat)&&p.name.toLowerCase().includes(q.toLowerCase()));$("#productGrid").innerHTML=arr.map(p=>`<article class="product-card" data-id="${p.id}"><div class="product-emoji">${p.emoji||"🍦"}</div><h3>${p.name}</h3><div class="price">${money(p.price)}</div><small class="${p.stock<=5?"stock-low":""}">${p.stock} stok tersedia</small></article>`).join("")||`<div class="empty"><div>🔎</div><b>Produk tidak ditemukan</b></div>`;$$(".product-card").forEach(c=>c.onclick=()=>addCart(c.dataset.id))}
function addCart(id){let p=state.products.find(x=>x.id===id);if(!p||p.stock<=0)return toast("Stok produk habis");let item=state.cart.find(x=>x.id===id);if(item){if(item.qty>=p.stock)return toast("Jumlah melebihi stok");item.qty++}else state.cart.push({id,qty:1});save();renderCart();toast(`${p.name} ditambahkan`)}
function renderCart(){let count=state.cart.reduce((a,x)=>a+x.qty,0);$("#cartCount").textContent=`${count} item`;if(!state.cart.length){$("#cartItems").innerHTML=`<div class="empty"><div>🍧</div><b>Keranjang masih kosong</b><span>Pilih es krim untuk mulai pesanan.</span></div>`}else $("#cartItems").innerHTML=state.cart.map(i=>{let p=state.products.find(x=>x.id===i.id);return `<div class="cart-item"><div class="cart-icon">${p.emoji}</div><div><h4>${p.name}</h4><small>${money(p.price)}</small><div class="qty"><button onclick="changeQty('${i.id}',-1)">−</button><b>${i.qty}</b><button onclick="changeQty('${i.id}',1)">＋</button></div></div><div class="cart-price">${money(p.price*i.qty)}</div></div>`}).join("");updateSummary()}
function changeQty(id,d){let i=state.cart.find(x=>x.id===id),p=state.products.find(x=>x.id===id);if(!i)return;i.qty+=d;if(i.qty>p.stock)i.qty=p.stock;if(i.qty<=0)state.cart=state.cart.filter(x=>x.id!==id);save();renderCart()}
function totals(){let sub=state.cart.reduce((a,i)=>{let p=state.products.find(x=>x.id===i.id);return a+p.price*i.qty},0);let pct=Math.max(0,Math.min(100,+$("#discountInput").value||0));return{sub,disc:sub*pct/100,total:sub-(sub*pct/100)}}
function updateSummary(){let t=totals();$("#subtotal").textContent=money(t.sub);$("#discount").textContent=money(t.disc);$("#total").textContent=money(t.total)}
function renderProductsTable(){let p=state.products;$("#productTotal").textContent=p.length;$("#lowStock").textContent=p.filter(x=>x.stock<=5).length;$("#stockValue").textContent=money(p.reduce((a,x)=>a+x.price*x.stock,0));$("#productTable").innerHTML=p.map(x=>`<tr><td><b>${x.emoji} ${x.name}</b></td><td>${x.category}</td><td>${money(x.price)}</td><td>${x.stock}</td><td><span class="badge ${x.stock<=5?"low":""}">${x.stock<=5?"Menipis":"Tersedia"}</span></td><td class="actions"><button onclick="editProduct('${x.id}')">Edit</button><button class="del" onclick="deleteProduct('${x.id}')">Hapus</button></td></tr>`).join("")}
function renderTransactions(){let rows=state.transactions;$("#transactionTable").innerHTML=rows.length?rows.slice().reverse().map(t=>`<tr><td><b>${t.id}</b></td><td>${new Date(t.time).toLocaleString("id-ID")}</td><td>${t.customer||"Umum"}</td><td>${t.type}</td><td>${t.items}</td><td><b>${money(t.total)}</b></td></tr>`).join(""):`<tr><td colspan="6" style="text-align:center;color:var(--muted)">Belum ada transaksi.</td></tr>`}
function renderReports(){let ts=state.transactions,rev=ts.reduce((a,t)=>a+t.total,0),items=ts.reduce((a,t)=>a+t.items,0);$("#reportRevenue").textContent=money(rev);$("#reportTransactions").textContent=ts.length;$("#reportItems").textContent=items;$("#reportAverage").textContent=money(ts.length?rev/ts.length:0);let cat={};let best={};ts.forEach(t=>t.lines.forEach(l=>{cat[l.category]=(cat[l.category]||0)+l.qty*l.price;best[l.name]=(best[l.name]||0)+l.qty}));let cats=Object.entries(cat).sort((a,b)=>b[1]-a[1]),max=Math.max(1,...cats.map(x=>x[1]));$("#categoryReport").innerHTML=cats.length?cats.map(x=>`<div class="report-line"><div><b>${x[0]}</b><div class="bar"><i style="width:${x[1]/max*100}%"></i></div></div><b>${money(x[1])}</b></div>`).join(""):`<div class="empty">Belum ada data</div>`;let bp=Object.entries(best).sort((a,b)=>b[1]-a[1]).slice(0,6);$("#bestProducts").innerHTML=bp.length?bp.map(x=>`<div class="report-line"><span>🍦 ${x[0]}</span><b>${x[1]} item</b></div>`).join(""):`<div class="empty">Belum ada data</div>`}
function showView(v){$$(".view").forEach(x=>x.classList.remove("active"));$(`#view-${v}`).classList.add("active");$$(".nav-item").forEach(x=>x.classList.toggle("active",x.dataset.view===v));let titles={pos:["Kasir","Kelola pesanan dengan cepat dan simpel."],products:["Produk","Kelola menu, harga, kategori, dan stok."],transactions:["Transaksi","Riwayat penjualan yang tersimpan di browser."],reports:["Laporan","Ringkasan performa penjualan FrostPOS."],settings:["Pengaturan","Sesuaikan identitas toko dan preferensi aplikasi."]};$("#pageTitle").textContent=titles[v][0];$("#pageSubtitle").textContent=titles[v][1];if(v==="products")renderProductsTable();if(v==="transactions")renderTransactions();if(v==="reports")renderReports();$("#sidebar").classList.remove("open")}
function openModal(id){$(id).classList.remove("hidden")}function closeModal(){ $$(".modal").forEach(x=>x.classList.add("hidden"))}
$$(".nav-item").forEach(b=>b.onclick=()=>showView(b.dataset.view));$("#mobileMenu").onclick=()=>$("#sidebar").classList.toggle("open");$$("[data-close]").forEach(x=>x.onclick=closeModal);$("#productSearch").oninput=()=>renderProducts($(".chip.active")?.dataset.cat||"Semua",$("#productSearch").value);$("#discountInput").oninput=updateSummary;$("#clearCart").onclick=()=>{state.cart=[];save();renderCart()};

let payMethod="Cash";$("#payBtn").onclick=()=>{if(!state.cart.length)return toast("Keranjang masih kosong");let t=totals();$("#paymentTotalText").textContent=`Total pembayaran: ${money(t.total)}`;$("#cashReceived").value=t.total;$("#change").textContent=money(0);openModal("#paymentModal")};$$(".method").forEach(b=>b.onclick=()=>{$$(".method").forEach(x=>x.classList.remove("active"));b.classList.add("active");payMethod=b.dataset.method;$("#cashReceived").disabled=payMethod!=="Cash";if(payMethod!=="Cash")$("#cashReceived").value=totals().total;calcChange()});$("#cashReceived").oninput=calcChange;
function calcChange(){let t=totals(),r=+$("#cashReceived").value||0;$("#change").textContent=money(Math.max(0,r-t.total))}
$("#confirmPayment").onclick=()=>{let t=totals(),r=+$("#cashReceived").value||0;if(payMethod==="Cash"&&r<t.total)return toast("Uang diterima belum cukup");let lines=state.cart.map(i=>{let p=state.products.find(x=>x.id===i.id);return{name:p.name,category:p.category,qty:i.qty,price:p.price}});state.cart.forEach(i=>{let p=state.products.find(x=>x.id===i.id);p.stock-=i.qty});state.transactions.push({id:"TRX-"+Date.now().toString().slice(-6),time:new Date().toISOString(),customer:$("#customerName").value,type:$("#orderType").value,method:payMethod,total:t.total,items:state.cart.reduce((a,x)=>a+x.qty,0),lines});state.cart=[];$("#customerName").value="";save();closeModal();renderProducts();renderCart();toast("Pembayaran berhasil disimpan ✓")};

$("#addProductBtn").onclick=()=>{openProductForm()};function openProductForm(p=null){$("#productModalTitle").textContent=p?"Edit Produk":"Tambah Produk";$("#editProductId").value=p?.id||"";$("#formName").value=p?.name||"";$("#formCategory").value=p?.category||"Ice Cream";$("#formPrice").value=p?.price||"";$("#formStock").value=p?.stock??"";$("#formEmoji").value=p?.emoji||"🍦";openModal("#productModal")}
$("#productForm").onsubmit=e=>{e.preventDefault();let id=$("#editProductId").value,p={id:id||"p"+Date.now(),name:$("#formName").value,category:$("#formCategory").value,price:+$("#formPrice").value,stock:+$("#formStock").value,emoji:$("#formEmoji").value||"🍦"};if(id){let i=state.products.findIndex(x=>x.id===id);state.products[i]=p}else state.products.push(p);save();renderCategories();renderProducts();renderProductsTable();closeModal();toast("Produk disimpan ✓")};
window.editProduct=id=>openProductForm(state.products.find(x=>x.id===id));window.deleteProduct=id=>{if(confirm("Hapus produk ini?")){state.products=state.products.filter(x=>x.id!==id);state.cart=state.cart.filter(x=>x.id!==id);save();renderCategories();renderProducts();renderProductsTable();renderCart();toast("Produk dihapus")}};window.changeQty=changeQty;

$("#exportBtn").onclick=()=>{let blob=new Blob([JSON.stringify(state.transactions,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download="frostpos-transactions.json";a.click();URL.revokeObjectURL(a.href);toast("Data transaksi diekspor")};
$("#resetDataBtn").onclick=()=>{if(confirm("Kembalikan produk demo? Transaksi akan tetap tersimpan.")){state.products=JSON.parse(JSON.stringify(demoProducts));save();renderCategories();renderProducts();renderProductsTable();renderCart();toast("Produk demo dipulihkan")}};
$("#saveSettings").onclick=()=>{state.settings.store=$("#storeName").value;state.settings.cashier=$("#cashierName").value;$("#cashierLabel").textContent=state.settings.cashier;save();toast("Pengaturan tersimpan ✓")};
$("#themeBtn").onclick=()=>{document.body.classList.toggle("dark");localStorage.setItem("frostTheme",document.body.classList.contains("dark")?"dark":"light");$("#themeBtn").textContent=document.body.classList.contains("dark")?"☀️":"🌙"};
if(localStorage.getItem("frostTheme")==="dark"){$("body").classList.add("dark");$("#themeBtn").textContent="☀️"}$("#storeName").value=state.settings.store;$("#cashierName").value=state.settings.cashier;$("#cashierLabel").textContent=state.settings.cashier;
function tick(){let d=new Date();$("#clock").textContent=d.toLocaleDateString("id-ID",{weekday:"short",day:"2-digit",month:"short"})+" • "+d.toLocaleTimeString("id-ID",{hour:"2-digit",minute:"2-digit"})}setInterval(tick,1000);tick();renderCategories();renderProducts();renderCart();
